name: Contracts PR CI

on:
  workflow_call:
    secrets:
      GH_NPM_TOKEN:
        required: true
      DEFAULT_NETWORK:
        required: true
      MNEMONIC:
        required: true
      MAINNET_RPC_URL:
        required: false
      KOVAN_RPC_URL:
        required: false
      GOERLI_RPC_URL:
        required: false
      RINKEBY_RPC_URL:
        required: false
      ROPSTEN_RPC_URL:
        required: false
      POLYGON_RPC_URL:
        required: false
      MUMBAI_RPC_URL:
        required: false
      ETHERSCAN_API_KEY:
        required: false
      CMC_KEY:
        required: false
      DISABLE_LOGS:
        required: false

jobs:
  test-contracts:
    runs-on: ubuntu-latest
    env:
      GH_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
    steps:
      - uses: teller-protocol/scaffold-pr-setup@main
        with:
          GH_NPM_TOKEN: ${{ env.GH_NPM_TOKEN }}

      - name: Create mnemonic secret
        run: echo ${{ secrets.MNEMONIC }} >> ./packages/hardhat-ts/mnemonic.secret

      - name: Test Contracts
        env:
          DEFAULT_NETWORK: ${{ secrets.DEFAULT_NETWORK }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          KOVAN_RPC_URL: ${{ secrets.KOVAN_RPC_URL }}
          GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
          RINKEBY_RPC_URL: ${{ secrets.RINKEBY_RPC_URL }}
          ROPSTEN_RPC_URL: ${{ secrets.ROPSTEN_RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
          MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          CMC_KEY: ${{ secrets.CMC_KEY }}
          DISABLE_LOGS: ${{ secrets.DISABLE_LOGS }}
        run: yarn test
